version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errorlint
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - tagliatelle
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
