output:
  sort-results: true
linters-settings:
  cyclop:
    max-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    - deadcode
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck
