FROM golang:1.18 AS build

# Cache module dependencies
COPY go.mod /trek/go.mod
COPY go.sum /trek/go.sum
WORKDIR /trek
RUN go mod download

# Add source and build the actual component
COPY ./cmd /trek/cmd
COPY ./internal /trek/internal
COPY ./main.go /trek
RUN go build -o dist/bin/trek .


FROM ghcr.io/printeers/pgmodeler:latest
COPY --from=build /trek/dist/bin/trek /usr/local/bin/trek

WORKDIR /data
