name: Publish docker images on version tag

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build migra
        run: ./internal/embedded/migra/build-migra.sh

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract trek metadata for Docker
        id: trek_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/printeers/trek
          tags: type=semver,pattern={{version}}-pgmodeler

      - name: Build and push trek Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.trek_meta.outputs.tags }}

      - name: Extract trek metadata for Docker
        id: trek_meta_suffixed
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/printeers/trek
          tags: type=semver,pattern={{version}}-pgmodeler

      - name: Build and push trek-pgmodeler Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.pgmodeler
          pull: true
          push: true
          tags: ${{ steps.trek_meta_suffixed.outputs.tags }}
